var lang = {
	common : {
		common_save: ["保 存", "Save"],
		common_saving: ["保存中, 请稍后...", "Saving, Please wait..."],
		common_fail : ["保存失败", "Settings are not saved!"],
		common_saved : ["保存成功", "Settings are saved!"],
		common_cancel : ["取消", "Cancel"],
		common_submit : ["确定", "Submit"],
		common_disable : ["禁用", "Disable"],
		common_enable : ["启用", "Enable"],
		common5 : ["上网设置", "Internet Setup"],
		common6 : ["网速控制", "Bandwidth Control"],
		common7 : ["USB应用", "USB"],
		common8 : ["系统管理", "Administration"],
		common_macErr1 : ["MAC地址错误,请输入正确的MAC地址!","Please enter a valid MAC address!"],
		common_macErr2 : ["MAC地址为组播地址,请重新输入!","The MAC address entered is a multicast address! Please retry!"],
		common_maskErr : ["请输入正确的子网掩码!", "Please specify a valid subnet mask!"]
	},
	login : {
		login1 : ["登录","Login"],
		login2 : ["选择语言","Language"],
		login3 : ["英文","English"],
		login4 : ["中文","Chinese"],
		login5 : ["密   码","Password"],
		login6 : ["默认：admin","Default: admin"],
		login7 : ["确 定","Login"],
		login_passErr1 : ["密码不能为空","Please enter the password!"],
		login_passErr2 : ["密码输入错误","Please enter a valid password!"]
	},
	main : {
		main_1 : ["上网设置", "Internet Setup"],
		main_2 : ["联网方式：", "Internet Connection Type: "],
		main_4 : ["联网状态：", "Internet Connection Status"],
		main_6 : ["信号放大", "Wireless Repeater"],
		main_7 : ["系统工具", "System Tools"],
		main_8 : ["软件版本：", "Firmware Version: "],
		main_9 : ["无线设置", "Wireless Setup"],
		main_10 : ["无线名称：", "SSID: "],
		main_11 : ["无线密码：", "Wireless Key: "],
		main_12 : ["上网管理", "Internet Manage"],
		main_14 : ["系统状态", "System Status"],
		main39 : ["(8-63位ASCII码或64位十六进制码,默认：12345678)", "(ASCII characters: 8~63; hex characters: 64; default: 12345678)"],
		main_connected : ["已连接", "Connected"],
		main_disconnected : ["未连接", "Disconnected"],
		main_connecting : ["连接中...", "Connecting..."],
		main_staticIp : ["静态IP","Static IP"],
		main_dhcp : ["动态IP","DHCP"],
		main_adsl : ["ADSL拨号","ADSL"],
		main_disabled : ["未启用","Disabled"],
		main_superSsid : ["中继信号：","Repeater Sign: "],
		main_ssid : ["无线名称：","SSID: "],
		main_ssidpwd : ["无线密码：","Wireless Key: "],
		main_wireErr : ["请插入网线","Please plug in the network cable!"],
		main_ssidErr : ["SSID未关联","SSID unassociated"],
		main_adslErr : ["ADSL用户名或密码错误","ADSL user name or password error"],
		main_forAdsl : ["建议使用ADSL拨号","Recommend the use of ADSL dial"],
		main_forDhcp : ["建议使用动态IP","Recommend using the dynamic IP"],
		
		main_show : ["显示密码", "Display"],
		main_hide : ["隐藏密码", "Hide"],
		main_ipErr : ["IP地址错误!", "Please enter a valid IP address!"],
		main_gatewayErr : ["网关错误!", "Please enter a valid gateway!"],
		main_dns1Err : ["DNS服务器错误!", "Please enter a valid Primary DNS Server!"],
		main_dns2Err : ["备用DNS服务器错误!", "Please enter a valid Secondary DNS Server!"],
		main_unername : ["请输入宽带用户名!", "Please enter the ISP user name!"],
		main_unernameErr : ["宽带用户名不支持中文字符!", "ISP user name cannot include Chinese characters!"],
		main_pwd : ["请输入宽带密码!", "Please enter the ISP password!"]
	},
	wanset : {
		wanset_1 : ["请使用运营商提供的宽带用户名和宽带密码拨号上网", "Please enter the ISP login user name and password."],
		wanset_2 : ["宽带用户名", "ISP User Name"],
		wanset_3 : ["宽带密码", "ISP Password"],
		wanset_4 : ["不需要任何配置,电脑自动获取运营商提供的上网信息", "No configurations are needed! The router automatically acquires IP information from your ISP."],
		wanset_5 : ["请使用运营商提供的固定IP地址等信息", "Please enter the static IP information provided by your ISP."],
		wanset_ip : ["IP地址", "IP Address"],
		wanset_subnet : ["子网掩码", "Subnet Mask"],
		wanset_gateway : ["网关", "Gateway"],
		wanset_dns1 : ["DNS服务器", "Primary DNS Server"],
		wanset_dns2 : ["备用DNS服务器(可选)", "Secondary DNS Server(Optional)"],
		wanset_adslErr1 : ["宽带用户名不能为空或含有 \' \" % \\ 等字符！", "ADSL user name can not be empty or contain \' \" % \\ characters such as!"],
		wanset_adslErr2 : ["宽带密码不能为空或含有 \' \" % \\ 等字符！", "ADSL password can not be empty or contain \' \" % \\ characters such as!"],
		wanset_MtuErr1 : ["MTU值设置不正确，必须为576到1492之间的数字", "MTU setting is not correct, must be between 576 to 1492 figures"],
		wanset_ipErr1 : ["IP 地址不能与登录IP在同一网段！", "IP address and login IP address can not be on the same IP segment!"],
		wanset_ipErr2 : ["默认网关不能与登录IP相同！", "Gateway can not be the same with the login IP address"],
		wanset_ipErr3 : ["IP 地址不能与默认网关或 DNS 服务器相同！", "IP address can not be the same as the default gateway or DNS server!"],
		wanset_MtuErr2 : ["MTU值设置不正确，必须为576到1500之间的数字", "MTU setting is not correct, must be between 576 to 1500 figures"]
	},
	wireless : {
		wireless_rate : ["无线频率", "Wireless Rate"],
		wireless_note : ["修改无线信号名称和密码需要先在电脑版网页中关闭wps", "Modify the wireless signal names and passwords need to turn off WPS on the computer"],
		wireless_popup : ["修改无线密码可能导致无线无法连接，建议同时修改无线信号名称", "Modify the wireless password may cause the wireless unable to connect, recommend to modify the name of the wireless signal"],
		wireless_ssid : ["请输入无线信号名称!", "Please enter an SSID (wireless network name)!"],
		wireless_ssid : ["请输入无线信号名称!", "Please enter an SSID (wireless network name)!"],
		wireless_ssidErr : ["无线信号名称最大长度为32位, 中文字符占3个字节", "The maximum length of the name of the wireless signal is 32, Chinese characters representing three bytes"],
		wireless_ssidErr2 : ["无线信号名称不支持中文字符!", "SSID cannot include Chinese characters!"],
		wireless_pwdEmpty : ["请输入无线密码", "Please enter a security key!"],
		wireless_wepErr : ["请输入5或13个ASCII, 或者10或26个十六进制码!", "Please enter 5 or 13 ASCII characters, or enter 10 or 26 Hex characters.!"],
		wireless_pwdErr : ["请输入无线密码,8-63位ASCII码或64位十六进制码!", "Please enter a security key! It can be 8~63 ASCII characters or 64 hex characters."],
		wireless_pwdNote1 : ["无线密码更改为 ", "Wireless password change to"],
		wireless_pwdNote2 : [", 需用新密码重新连接路由器！确认更改吗？", ", new password required to reconnect the router! Confirm changes?"],
		wireless_roamNote : ["无线漫游已开启，若继续保存无线漫游将关闭！", "Wireless roaming turned on, if it continues to save the wireless roaming will close!"]
	},
	client : {
		client_manage : ["客户端管理", "Client Management"],
		client_host : ["主机名称", "Hostname"],
		client_net : ["上网管理", "Network Control"],
		client_allow : ["允许", "Allow"],
		client_forbid : ["禁止", "Forbid"],
		client_connect : ["确认连接 ", "Confirm the connection"]
	},
	
	wisp : {
		wisp_sign : ["无线信号放大", "WISP"],
		wisp_wander : ["无线漫游", "Wireless Roaming"],
		wisp_select : ["选择网络", "Select Internet"],
		wisp_note : ["点击连接后，设备将自动重启使配置生效", "Click on the link, the device will automatically restart the configuration to take effect"],
		wisp_cancel : ["取消", "Cancel"],
		wisp_connect : ["连接", "Connect"],
		wisp_savenote: ["请在首页或系统工具查看连接状态!"," Please check the connection status on the home page or system tools!"],
		usb_username : ["用户名最长12位,只能含字母,数字,下划线!", "User name can only include up to 12 characters (letters, numbers and underscore only)."],
		usb_password : ["请输入正确的密码,最长12位,只能含字母,数字,下划线!", "Please enter a correct password! It can consist of up to 12 characters (letters, numbers and underscore only)."]
	},
	systool: {
		systool_info : ["联网信息", "Internet Connection"],
		systool_conState : ["联网状态", "Internet Connection Status"],
		systool_conType : ["联网方式", "Internet Connection Type"],
		systool_conTime : ["连接时间", "Connection Duration"],
		systool_reboot : ["重启路由器","Reboot"],
		systool_restore : ["恢复出厂设置","Restore to Factory Default"],
		systool_upgrade : ["软件升级","Fireware Upgrade"],
		systool_password : ["设置登录密码","Setup Password"],
		systool_oldpwd : ["输入旧密码", "Old Password"],
		systool_newpwd : ["新密码", "New Password"],
		systool_newpwd2 : ["确认新密码", "Confirm New Password"],
		systool_mac : ["设置WAN口MAC","MAC Clone"],
		systool_macClone : ["克隆本机MAC","MAC Clone"],
		systool_macRestore : ["恢复出厂MAC","Restore to Factory Default"],
		systool_restoreNote : ["设备恢复出厂设置后,请注意以IP 192.168.189.1进行登录!","After the device is restored to factory settings, use the IP address of 192.168.189.1 to re-log in to the device."],
		systool_restoreNote1 : ["恢复出厂设置将清除当前所有配置.</br>设备重启中...","Restore the factory settings will clear all current configuration.</ br> Device rebooting ..."],
		systool_rebootNote : ["重启完成后需要连接无线信号才能继续操作.</br>设备重启中...","Need to reconnect the wireless signal after the router reboot is complete.</ br> Device rebooting ..."],
		systool_rebootConfirm : ["您确定要重启路由器吗？","Are you sure you want to reboot your device?"],
		//system_newErr : ["新密码输入错误!","Please enter a valid new password!"],
		systool_pwdErr1 : ["原始密码不正确。","Please enter a correct old password!"],
		systool_pwdErr2 : ["新密码至少3位","The new password length of at least 3"],
		systool_pwdErr3 : ["两次密码输入不一致","Passwords mismatched!"],
		systool_saveNote : ["数据保存中,功能在重启后生效.","Data saving, function after the restart to take effect."],
		systool_connectStatus : ["连接状态","Connected Status"],
		systool_time : ["系统时间","System Time"],
		systool_version : ["系统版本","System Version"],
		systool_upgradeErr1 : ["请选择升级文件。","Please select a firmware file!"],
		systool_upgradeErr2 : ["升级文件有误，请确保文件的正确。","Firmware file is incorrect, please make sure that the correct file."],
		systool_upgradeNote : ["升级中，大约需要2分钟，请稍候。","Upgrading... It will takes about two minutes, please wait."],
		systool_upgradeNote2 : ["注意：升级时不能关闭路由器的电源，否则将导致路由器损坏，升级成功后，路由器将自动重启。","Note: Do not turn off the router's power when upgrading, otherwise it will cause damage to the router, after the upgrade is successful, the router will automatically restart."],
		systool_selectFile : ["选择文件", "Select Firmware"],
	},
	system : {
		system1 : ["设置登录密码", "Login Password Setup"],
		system3 : ["密码只能由1-12个字母或数字组成!", "Password must be 1~12 alpha-numeric characters!"],
		system8 : ["LAN口设置", "LAN Setup"],
		system10 : ["设置登录IP地址", "Login IP"],
		system11 : ["启用DHCP服务器", "Enable DHCP Server"],
		system22 : ["启用DHCPv6服务器", "Enable DHCPv6 Server"],
		system23 : ["无状态","Stateless"],
		system24 : ["有状态","Stateful"],
		system28 : ["启用RADVD", "Enable RADVD"],
		system29 : ["WAN口参数", "WAN Parameter"],
		system30 : ["MAC地址克隆", "MAC Clone"],
		system31 : ["克隆", "Clone"],
		system32 : ["恢复默认", "Restore Factory Settings"],
		system33 : ["网络协议", "Network Protocol"],
		system34 : ["协议", "Protocol"],
		system36 : ["设备管理", "Device Management"],
		system37 : ["重启路由", "Reboot Device"],
		system38 : ["立即重启", "Reboot Now"],
		system39 : ["恢复出厂设置", "Restore Factory Settings"],
		system40 : ["恢复出厂", "Restore Factory Settings"],
		system41 : ["启用日志服务器", "Enable Log Server"],
		system42 : ["导出日志", "Export Logs"],
		
		system45 : ["请选择正确的升级文件,否则升级失败,路由器重启", "If a wrong firmware is selected, upgrade fails and the device restarts."],
		system_dhcp : ["动态IP","Dynamic IP"],
		system_static : ["静态IP","Static IP"],
		system_day : ["天","Day"],
		system_reboot : ["设备正在重启,请稍候...","Rebooting...Please wait!"],
		system_upgrad : ["设备正在升级,请勿关闭电源...","Upgrading... Please do NOT interrupt power connection!"],
		system_version : ["当前软件版本：","Current Firmware Version:"],
		system_rebootNote : ["大约45秒后系统会重新链接至首页.","System will return to home page in about 45 or more seconds."],
		system_rebooting : ["正在重启中...","Rebooting"],
		system_upgradeNote : ["您确信要升级吗?","Are you sure you want to update your device?"],
		system_upgrading : ["正在升级中...","Upgrading"],
		system_upgradeFail : ["升级失败,重启路由器","Firmware upgrade fails! Device will restart."],
		system_restore : ["正在恢复出厂设置并重启...","Restoring factory settings and restarting..."],
		system_log : ["导出配置参数,请指定保存参数的路径!","Please select a directory before exporting settings!"],
		system_loginIp : ["登录IP地址错误","The login IP address is incorrect!"],
		system_permanent : ["永久","Permanent"],
		system_startIp : ["开始IP地址错误","The start IP address is incorrect!"],
		system_endIp : ["结束IP地址错误","The end IP address is incorrect!"],
		system_newErr2 : ["新确认密码输入错误!","Passwords are mismatched!"],
		system_ipErr1 : ["开始IP必须小于结束IP!","Start IP should NOT be greater than end IP!"],
		system_ipErr2 : ["登录IP地址与开始IP地址不在同一网段!","Login IP address and start IP address must be on the same IP segment!"],
		system_ipErr3 : ["开始IP地址与结束IP地址不在同一网段!","Start IP and end IP addresses must be on the same IP segment!"],
		system_ipErr4 : ["IP地址有误","Please enter a valid IP address!"],
		system_pwdNote : ["路由器的登陆密码改变,需重新登陆验证密码","The device's login password has been changed. New password authentication is required."],
		system_pinErr : ["必须输入8位数字", "Must be 8 Numbers"]
		//system_ipChange1 : ["路由器IP地址发生改变,请使用","The device's IP address has been changed to"],
		//system_ipChange2 : ["重新登录,并配置相关参数.","Please log in to the device again and update related settings!"]
	}
}
